#

pluginName = LaBouR Edit Support
providerName = www.example.org

_UI_CreateChild_text = {0}
_UI_CreateChild_text2 = {1} {0}
_UI_CreateChild_text3 = {1}
_UI_CreateChild_tooltip = Create New {0} Under {1} Feature
_UI_CreateChild_description = Create a new child of type {0} for the {1} feature of the selected {2}.
_UI_CreateSibling_description = Create a new sibling of type {0} for the selected {2}, under the {1} feature of their parent.

_UI_PropertyDescriptor_description = The {0} of the {1}

_UI_BoulderingWall_type = Bouldering Wall
_UI_Hold_type = Hold
_UI_Route_type = Route
_UI_Label_type = Label
_UI_Start_hold_type = Start hold
_UI_End_hold_type = End hold
_UI_Shape_type = Shape
_UI_Circle_type = Circle
_UI_Triangle_type = Triangle
_UI_Corner_type = Corner
_UI_ExtrusionPoint_type = Extrusion Point
_UI_Volume_type = Volume
_UI_GridBasePointer_type = Grid Base Pointer
_UI_RouteStep_type = Route Step
_UI_SplitStep_type = Split Step
_UI_SingleStep_type = Single Step
_UI_Unknown_type = Object

_UI_Unknown_datatype= Value

_UI_BoulderingWall_ID_feature = ID
_UI_BoulderingWall_hold_feature = Hold
_UI_BoulderingWall_route_feature = Route
_UI_BoulderingWall_volume_feature = Volume
_UI_Hold_ID_feature = ID
_UI_Hold_x_feature = X
_UI_Hold_y_feature = Y
_UI_Hold_Color_feature = Color
_UI_Hold_Rotation_feature = Rotation
_UI_Hold_label_feature = Label
_UI_Hold_shape_feature = Shape
_UI_Route_ID_feature = ID
_UI_Route_Grade_feature = Grade
_UI_Route_gridbasepointer_feature = Gridbasepointer
_UI_Route_steps_feature = Steps
_UI_Start_hold_Arg_feature = Arg
_UI_Circle_x_feature = X
_UI_Circle_y_feature = Y
_UI_Circle_Radius_feature = Radius
_UI_Circle_Depth_feature = Depth
_UI_Circle_front_holds_feature = Front holds
_UI_Circle_side_holds_feature = Side holds
_UI_Triangle_x_feature = X
_UI_Triangle_y_feature = Y
_UI_Triangle_corner_feature = Corner
_UI_Triangle_extrusionpoint_feature = Extrusionpoint
_UI_Triangle_Depth_feature = Depth
_UI_Triangle_left_holds_feature = Left holds
_UI_Triangle_right_holds_feature = Right holds
_UI_Triangle_bottom_holds_feature = Bottom holds
_UI_Corner_y_feature = Y
_UI_Corner_x_feature = X
_UI_ExtrusionPoint_x_feature = X
_UI_ExtrusionPoint_y_feature = Y
_UI_Volume_shape_feature = Shape
_UI_GridBasePointer_x_feature = X
_UI_GridBasePointer_y_feature = Y
_UI_SplitStep_left_feature = Left
_UI_SplitStep_right_feature = Right
_UI_SingleStep_hold_feature = Hold
_UI_Unknown_feature = Unspecified

_UI_Colors_RED_literal = RED
_UI_Colors_GREEN_literal = GREEN
_UI_Colors_PURPLE_literal = PURPLE
_UI_Colors_BLUE_literal = BLUE
_UI_Colors_WHITE_literal = WHITE
_UI_Colors_PINK_literal = PINK
_UI_Colors_BLACK_literal = BLACK
_UI_Colors_YELLOW_literal = YELLOW
_UI_Colors_ORANGE_literal = ORANGE
